// GENERATED by scripts/generate-font-subsets.mjs -- do not edit.
// Run `npm run fonts:subset` after changing the characters in that script.

/** ZCOOL XiaoWei, subset to: 因为热爱 */
export const ZCOOL_RANGE = "U+4e3a, U+56e0, U+70ed, U+7231";

/** Inter, subset to: @ */
export const AT_RANGE = "U+40";
